# Generated by Django 4.0.3 on 2022-12-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0002_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
